Upload Session-8
Pseudo-Lab/data-engineering-for-everybody pull request #42
Opened 2023-07-12 13:44 UTC by Steve-YJ

## 상세
* Session-8 Cloud Computing 미업로드분 업로드 진행했습니다.
* 로컬 환경에서 빌드 해봤으며 이상 없었습니다!
* 기존에 session-8 브랜치가 존재했지만 업로드한 이력이 없기에 해당 커밋을 바로 반영하도록 하겠습니다.
* 이슈 발생시 복구하도록 하겠습니다.

2023-07-15 01:55 UTC, ehddnr301 requested changes
참고자료 부분에 오류가 있는것 같습니다ㅜㅜ

<img width="844" alt="image" src="https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/54092915/c69a88d3-4c78-40a6-bfaa-7a60c55ea219">

<img width="450" alt="image" src="https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/54092915/08fb0f9d-cd2b-4a73-8307-5773446ebd6d">

<img width="656" alt="image" src="https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/54092915/81153f33-5c80-4a31-838e-525d12920754">

2023-07-17 13:35 UTC, heehehe approved these changes
영전님 정말 수고 많으셨습니다!!
내용들 살펴보면서 조금 세세하게 리뷰해보긴 했는데, 
무조건 코멘트대로 다 반영될 필요는 없을 것 같고 참고만 해주시면 감사하겠습니다 :)

2023-07-17 13:35 UTC, heehehe commented on book/docs/8_cloud_computing_and_data_engineering/8.1_cloud_computing.md
> +`문제점`
통일성을 위해 header 부분(?)에는 코드블록을 없애면 어떨까 싶습니다..!

2023-07-17 13:35 UTC, heehehe commented on book/docs/8_cloud_computing_and_data_engineering/8.1_cloud_computing.md
> +- 관리는 HOST가..
해당 부분이 설명 없이 글로만 봤을때 저는 이해하기가 약간 어려운 것 같아서요ㅠㅠ
조금만 더 구체적으로 설명되면 좋을 것 같습니다..!😃

2023-07-17 13:35 UTC, heehehe commented on book/docs/8_cloud_computing_and_data_engineering/8.2_data_engineering.md
이번 PR에서의 수정사항은 아니지만, 설명 부분이 이미지 위쪽으로 올라가면 보기 더 편할 것 같습니다!
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/41580746/82d447da-bc21-4a29-bd92-fb02161a3c66)

2023-07-17 13:35 UTC, heehehe commented on book/docs/8_cloud_computing_and_data_engineering/8.4_use_case_cloud_dataengineering.md
> +> 1.Amplitude file이 GCS(Google Cloud Storage)에 적재되고, 매일 오전 7시마다 GCP Dataproc 에서 Spark를 통해 데이터를 가공하여 분석하기 용이한 형태로 BigQuery에 데이터 마팅을 진행합니다.
`>` 부분이 제거되어야 할 것 같아요!
![image](https://github.com/Pseudo-Lab/data-engineering-for-everybody/assets/41580746/80e6564d-6f52-4a31-98d3-527a9ee9e561)

2023-07-17 13:35 UTC, heehehe commented on book/docs/8_cloud_computing_and_data_engineering/8.5_multi_cloud_dataengineering.md
> +멀티클라우드간 실시간 데이터 전송을 쉽게 구성해주는 SaaS형 서비스도 존재합니다. 하지만 쉬운 방법이 지금 조직과 팀의 상황, 네트워크.보안 등을 고려하면 최적의 솔루션이 아닐 수도 있습니다.
(사소한 부분이긴 하지만..😅) `네트워크.보안` → `네트워크, 보안` 으로 되어야 할 것 같습니다!

2023-07-17 13:35 UTC, heehehe commented on book/docs/8_introduction_to_apache_airflow/template_main_page.md
> +# 8. Introduction to Apache Airflow
airflow 세션은 7번이 되어야 할 것 같은데 맞을까요..?!

2023-07-18 12:02 UTC, Steve-YJ commented on book/docs/8_cloud_computing_and_data_engineering/8.1_cloud_computing.md
> +`문제점`
의견 주셔서 감사합니다! 이부분을 놓치고 있었네요!
반영하는게 좋을 것 같습니다! 감사합니다 :)

2023-07-18 12:03 UTC, Steve-YJ commented on book/docs/8_cloud_computing_and_data_engineering/8.1_cloud_computing.md
> +- 관리는 HOST가..
넵 희선님 의견 주셔서 감사합니다!
해당 콘텐츠는 민행님께서 작성해주신 부분인데요... 조금 더 설명을 더하면 좋을 것 같네요!
조금 더 모두를 위한 데이터 엔지니어링에 가깝도록 수정하도록 하겠습니다! :)

2023-07-18 12:04 UTC, Steve-YJ commented on book/docs/8_introduction_to_apache_airflow/template_main_page.md
> +# 8. Introduction to Apache Airflow
넵 맞습니다! airflow 세션은 7번으로 수정되어야 합니다!
리뷰 너무 꼼꼼하게 잘 봐주셔서 정말 감사합니다! 💯

2023-07-18 13:39 UTC, heehehe approved these changes

2023-07-21 04:04 UTC, merged